<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	<RootNamespace>TerminalStuff</RootNamespace>
	<AssemblyName>darmuhsTerminalStuff</AssemblyName>
	<AssemblyTitle>darmuhsTerminalStuff</AssemblyTitle>
	<Version>3.10.0</Version>
	<AssemblyVersion>3.10.0</AssemblyVersion>
	<Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

	<!-- EmbeddedResource assets-->
  <ItemGroup>
    <EmbeddedResource Include="Assets\hidden169" />
  </ItemGroup>
  <ItemGroup>
    <Reference Update="OpenLib">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
