<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	<RootNamespace>TerminalStuff</RootNamespace>
	<AssemblyName>darmuhsTerminalStuff</AssemblyName>
	<Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="darmuhngo" />
  </ItemGroup>

	<!-- EmbeddedResource assets-->
  <ItemGroup>
    <EmbeddedResource Include="Assets\hidden169"/>
    <EmbeddedResource Include="darmuhngo" />
  </ItemGroup>

</Project>
